name: CustomInventories
version: ${project.version}
main: me.wiviw.custominventories.CustomInventories
load: STARTUP
depend: [ BountifulAPI ]
authors: [ WiViW ]
description: Custom Inventories and other fun features.
commands:
  gm:
    description: Toggles your gamemode between the two main ones.
  gms:
    description: Sets your gamemode to Survival.
  gmc:
    description: Sets your gamemode to Creative.
  gmss:
    description: Sets your gamemode to Spectator.
  gma:
    description: Sets your gamemode to Adventure.
  returntext:
    description: Returns Text to only yourself.
  returntextall:
    description: Returns Text to everyone.
  rename:
    description: Renames an item.
  relore:
    description: Relores an item.
  toggleextras:
    description: Toggles many diffrent aspects.
  particletrails:
    description: Particle Trails.
  colorleather:
    description: Colors leather armor.
  sethealth:
    description: Sets your Health.
  inventory:
    description: Opens an Inventory
  glowing:
    description: makes an item glow like it is enchanted.
  colorcodes:
    description: A chat feature for all the color descriptions you would ever need!
  head:
    description: Gives you a head.
  setlevel:
    description: Sets Certain Aspects about your xp bar.